export type FieldEntry = {
  name: string
  uscfId: string
  uscfRating: number
  fideRating: number | null
  state: string
  schedule: '2 Day' | '3 Day' | '4 Day'
  withdrawn?: boolean
  isPlayer?: boolean
  notes: string
}

export const nysChampionship = {
  title: '148th NY State Championship',
  shortTitle: 'NYS Championship',
  location: 'Albany Marriott, Albany, NY',
  startDate: '2026-09-04',
  endDate: '2026-09-07',
  rounds: 6,
  timeControl: '40/80, SD/30; d30',
  section: 'Championship (1900+)',
  format: '6-round Swiss · September official USCF ratings',
  entryListUrl:
    'https://chessaction.com/tournaments/advance_entry_list.php?tid=nKOlog%3D%3D',
  infoUrl: 'https://www.chesstour.com/nysc26.htm',
  fieldSnapshotDate: '2026-09-02',
  schedule: [
    { label: '4-day R1', when: 'Fri Sep 4, 7:00 PM' },
    { label: 'Merge / R2', when: 'Sat Sep 5, 6:00 PM' },
    { label: 'R3', when: 'Sun Sep 6, 12:00 PM' },
    { label: 'R4', when: 'Sun Sep 6, 6:00 PM' },
    { label: 'R5', when: 'Mon Sep 7, 10:00 AM' },
    { label: 'R6', when: 'Mon Sep 7, 3:30 PM' },
  ],
  field: [
    {
      name: 'Josiah Stearman',
      uscfId: '14006506',
      uscfRating: 2551,
      fideRating: 2464,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Igor Sorkin',
      uscfId: '12684250',
      uscfRating: 2423,
      fideRating: 2354,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Jasmine Su',
      uscfId: '16377701',
      uscfRating: 2356,
      fideRating: 2235,
      state: 'CT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Priyansh Garg',
      uscfId: '17279963',
      uscfRating: 2271,
      fideRating: 2122,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Jay Richard Bonin',
      uscfId: '10098327',
      uscfRating: 2263,
      fideRating: 2087,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Alisher Podavonov',
      uscfId: '14655085',
      uscfRating: 2251,
      fideRating: 2106,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Nelson Castaneda',
      uscfId: '12564228',
      uscfRating: 2248,
      fideRating: 2168,
      state: 'CT',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Leo Xiaohang Shen',
      uscfId: '17132332',
      uscfRating: 2243,
      fideRating: 2147,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'James J Marsh',
      uscfId: '16400887',
      uscfRating: 2242,
      fideRating: 2134,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Landon Meadors',
      uscfId: '31453265',
      uscfRating: 2231,
      fideRating: 1995,
      state: 'DE',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Royce Zhang',
      uscfId: '30154455',
      uscfRating: 2228,
      fideRating: 2112,
      state: 'RI',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Lucas Lu',
      uscfId: '17119897',
      uscfRating: 2207,
      fideRating: 2072,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'David E Carter',
      uscfId: '10029732',
      uscfRating: 2202,
      fideRating: 1921,
      state: 'VT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Alan Shaw',
      uscfId: '10030048',
      uscfRating: 2200,
      fideRating: 2137,
      state: 'VT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'John Riddell',
      uscfId: '10084369',
      uscfRating: 2200,
      fideRating: 1964,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Alex Sinnott',
      uscfId: '13513605',
      uscfRating: 2188,
      fideRating: 1937,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Neil Natarajan',
      uscfId: '30048585',
      uscfRating: 2182,
      fideRating: 2015,
      state: 'CT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Kushagra Bhargava',
      uscfId: '16956146',
      uscfRating: 2167,
      fideRating: 2016,
      state: 'CT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Mark Dedona',
      uscfId: '14684907',
      uscfRating: 2165,
      fideRating: 1980,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Armaan Chandragupta Jain',
      uscfId: '30230374',
      uscfRating: 2158,
      fideRating: 1896,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Brian Arthur',
      uscfId: '14176605',
      uscfRating: 2157,
      fideRating: 1925,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Marzouq Chowdhury',
      uscfId: '31319470',
      uscfRating: 2154,
      fideRating: 2024,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Connor Junda Wang',
      uscfId: '16470052',
      uscfRating: 2132,
      fideRating: 1946,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Adam Gordon',
      uscfId: '16577100',
      uscfRating: 2131,
      fideRating: 1933,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Justin Lee',
      uscfId: '16713783',
      uscfRating: 2128,
      fideRating: 1946,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Mubassar Uddin',
      uscfId: '14603572',
      uscfRating: 2128,
      fideRating: 2000,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Samuel Pozen',
      uscfId: '16509885',
      uscfRating: 2120,
      fideRating: 1965,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Edison Burgos Rodriguez',
      uscfId: '12542136',
      uscfRating: 2100,
      fideRating: 1795,
      state: '',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Steven A Taylor',
      uscfId: '11282008',
      uscfRating: 2100,
      fideRating: 1822,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Jude Kazan',
      uscfId: '16350155',
      uscfRating: 2095,
      fideRating: 1821,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Leonhard Chang',
      uscfId: '17018215',
      uscfRating: 2094,
      fideRating: 2002,
      state: 'NJ',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Alice Chovanec',
      uscfId: '16898466',
      uscfRating: 2090,
      fideRating: 1814,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Arabella Fang',
      uscfId: '16483587',
      uscfRating: 2087,
      fideRating: 1968,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Supreetha Potluri',
      uscfId: '16053696',
      uscfRating: 2087,
      fideRating: 1904,
      state: '',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Theodore Bernstein',
      uscfId: '31096166',
      uscfRating: 2075,
      fideRating: 1949,
      state: 'NJ',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Jin Ma',
      uscfId: '16813308',
      uscfRating: 2070,
      fideRating: 1859,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Charles Huang',
      uscfId: '30427161',
      uscfRating: 2067,
      fideRating: 1971,
      state: 'MA',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Jason Bai',
      uscfId: '30173780',
      uscfRating: 2067,
      fideRating: 1824,
      state: 'CT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Mark Leo Kogan',
      uscfId: '30053068',
      uscfRating: 2062,
      fideRating: 1920,
      state: 'NJ',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Jeremiah Beckles',
      uscfId: '16109946',
      uscfRating: 2060,
      fideRating: 1847,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Matt Chan',
      uscfId: '13910194',
      uscfRating: 2055,
      fideRating: 1875,
      state: 'CT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Adrian Harrison Sommerstein',
      uscfId: '30575100',
      uscfRating: 2051,
      fideRating: 1836,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Leon Chu',
      uscfId: '17015896',
      uscfRating: 2043,
      fideRating: 1877,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Theodore V Pimanoff',
      uscfId: '17124861',
      uscfRating: 2035,
      fideRating: 1866,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Samuel Nemiroff',
      uscfId: '17055610',
      uscfRating: 2034,
      fideRating: 1746,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Misha Raitzin',
      uscfId: '16170786',
      uscfRating: 2023,
      fideRating: 1780,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Allyson Yu',
      uscfId: '30721310',
      uscfRating: 2022,
      fideRating: 1821,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Premsai Nallapareddygari',
      uscfId: '31083400',
      uscfRating: 2020,
      fideRating: 1786,
      state: 'NJ',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Winston Ruiying Chen',
      uscfId: '31394432',
      uscfRating: 2015,
      fideRating: 1808,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Harry Li',
      uscfId: '16988211',
      uscfRating: 2011,
      fideRating: 1825,
      state: 'MA',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Alek Safarian',
      uscfId: '32544394',
      uscfRating: 2002,
      fideRating: 1892,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Dore A Sheppard',
      uscfId: '10076692',
      uscfRating: 2001,
      fideRating: 1877,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Eric Ren',
      uscfId: '16753438',
      uscfRating: 2001,
      fideRating: 2004,
      state: 'CT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Eric Cheng',
      uscfId: '16921202',
      uscfRating: 1997,
      fideRating: 1801,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'David Johnathan Carr',
      uscfId: '30315361',
      uscfRating: 1995,
      fideRating: 1752,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Derek Li Chen',
      uscfId: '14883880',
      uscfRating: 1990,
      fideRating: 1859,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Jeremy Zheng',
      uscfId: '14973085',
      uscfRating: 1990,
      fideRating: null,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Angel Lopez',
      uscfId: '12833885',
      uscfRating: 1988,
      fideRating: 1920,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Marissa Lu',
      uscfId: '17119902',
      uscfRating: 1983,
      fideRating: 1898,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Myra Nigam',
      uscfId: '31420695',
      uscfRating: 1982,
      fideRating: 1845,
      state: 'PA',
      schedule: '4 Day',
      notes: 'Byes: 1/2:R1',
    },
    {
      name: 'Milo Su',
      uscfId: '31296341',
      uscfRating: 1970,
      fideRating: 1777,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Nirupam Kushalnagar',
      uscfId: '17349316',
      uscfRating: 1967,
      fideRating: 1858,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Jesse Hoffman',
      uscfId: '14804351',
      uscfRating: 1966,
      fideRating: 1828,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Kristian Jacome',
      uscfId: '14531740',
      uscfRating: 1966,
      fideRating: 1748,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Liam Siu',
      uscfId: '30022059',
      uscfRating: 1959,
      fideRating: 1812,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Melanie Liang',
      uscfId: '30351272',
      uscfRating: 1959,
      fideRating: 1811,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Charles B Bernstein',
      uscfId: '31390648',
      uscfRating: 1958,
      fideRating: 1762,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Darren Wu',
      uscfId: '30136086',
      uscfRating: 1955,
      fideRating: 1741,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Dean',
      uscfId: '31329150',
      uscfRating: 1954,
      fideRating: null,
      state: 'NY',
      schedule: '4 Day',
      isPlayer: true,
      notes: '4-day Championship. Entry-list Regular 1954.',
    },
    {
      name: 'Charlotte Tai-en Chang',
      uscfId: '31490450',
      uscfRating: 1953,
      fideRating: 1870,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Grayson Xiang',
      uscfId: '30650149',
      uscfRating: 1946,
      fideRating: 1907,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Shiv Dubey',
      uscfId: '17241381',
      uscfRating: 1942,
      fideRating: 1752,
      state: 'NY',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Christian Mingdong Wang',
      uscfId: '32054208',
      uscfRating: 1928,
      fideRating: 1838,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Wilson Liu',
      uscfId: '30799156',
      uscfRating: 1917,
      fideRating: 1639,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Aiden Zhu',
      uscfId: '31945797',
      uscfRating: 1916,
      fideRating: 1802,
      state: 'NC',
      schedule: '4 Day',
      notes: '',
    },
    {
      name: 'Eugene Wong',
      uscfId: '17157923',
      uscfRating: 1915,
      fideRating: 1675,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Calliste Herve-mignucci',
      uscfId: '16787928',
      uscfRating: 1913,
      fideRating: 1767,
      state: 'CT',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Michael Semel',
      uscfId: '12394665',
      uscfRating: 1900,
      fideRating: 1677,
      state: 'NY',
      schedule: '3 Day',
      notes: '',
    },
    {
      name: 'Jianchao Zhou (GM)',
      uscfId: '15524414',
      uscfRating: 2657,
      fideRating: 2575,
      state: 'MA',
      schedule: '3 Day',
      withdrawn: true,
      notes: 'Withdrawn on the advance-entry list.',
    },
    {
      name: 'Alvin Lou',
      uscfId: '30228821',
      uscfRating: 1954,
      fideRating: 1768,
      state: 'NY',
      schedule: '3 Day',
      withdrawn: true,
      notes: 'Withdrawn on the advance-entry list.',
    },
  ] satisfies FieldEntry[],
} as const

export type NysChampionship = typeof nysChampionship

export function daysUntilEventStart(isoDate: string, now = Date.now()): number {
  const start = new Date(`${isoDate}T19:00:00-04:00`)
  return Math.ceil((start.getTime() - now) / 86_400_000)
}
